apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
  labels:
    app: posts
    tier: backend
    environment: development
  annotations:
    description: "Deployment for the posts service"
    owner: "selected Group"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: cygnetops/posts-71:0.0.1
